apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: authservice-pvc
  namespace: istio-system
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
