apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: katib-mysql
  namespace: kubeflow
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
